name: GreenRwanda
favicon: null
layout_spectrum: 0.26118
typography_spectrum: 0.47931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5a4b45'
    - '#3eb34f'
    - '#968e8a'
    - '#d4d1ce'
  brandStrength: 0.8257684614509344
  lightness: 0.9736722498200834
  saturation: 0.09085905691608787
  rhythmicContrast: 0.17958335718140006
purpose: []
